---
title: "Análisis de la relación entre estadísticas de equipos de la NBA con más y menos victorias durante períodos de nueve años comprendido entre 1996 y 2023"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill 
---
```{r Chunk_principal, include=FALSE}
library(flexdashboard)
library(plotly)
library(tidyverse)
library(DT)
library(shiny)
NBA_G1_1_<- read_csv("C:/Users/Luis/Downloads/NBA G1 (1).xlsx")
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(gridExtra)
library(knitr)
library(dplyr)
library(readxl)
NBA_G1_1_ <- read_excel("C:/Users/Luis/Downloads/NBA G1 (1).xlsx")
View(NBA_G1_1_)
df <- NBA_G1_1_
df <- df %>%
  mutate(season_by_period=case_when(
    SEASON %in% c('2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2020-21', '2021-22', '2022-23') ~ "period 3",
    SEASON %in% c('2005-06', '2006-07', '2007-08', '2008-09', '2009-10', '2010-11', '2011-12', '2012-13', '2013-14') ~ "period 2",
    SEASON %in% c('1996-97', '1997-98', '1998-99', '1999-00', '2000-01', '2001-02', '2002-03', '2003-04', '2004-05') ~ "period 1",
    TRUE ~ "other"
  ))


team_by_period_w_prom <- df %>% group_by(TEAM, season_by_period) %>% summarise(w_prom = mean(W))

w_period_1 <- filter(team_by_period_w_prom, season_by_period == 'period 1')

w_period_1 <- w_period_1[order(w_period_1$w_prom, decreasing = TRUE),]


w_period_2 <- filter(team_by_period_w_prom, season_by_period == 'period 2')

w_period_2 <- w_period_2[order(w_period_2$w_prom, decreasing = TRUE),]


w_period_3 <- filter(team_by_period_w_prom, season_by_period == 'period 3')

w_period_3 <- w_period_3[order(w_period_3$w_prom, decreasing = TRUE),]
#Dataframes de los equipos por períodos con todas las variables#

df_period1 <- df %>% filter(season_by_period=="period 1") %>% filter(TEAM=="Los Angeles Lakers"|TEAM=="Golden State Warriors")
df_period2 <- df %>% filter(season_by_period=="period 2") %>% filter(TEAM=="San Antonio Spurs"|TEAM=="Minnesota Timberwolves")
df_period3<- df %>% filter(season_by_period=="period 3") %>% filter(TEAM=="Golden State Warriors"|TEAM=="Orlando Magic")
w_period_3_ <- w_period_3 %>% filter(w_prom < 56)

```
Portada
============================================================================
Column {data-heigth=300}
-----------------------------------------------------------------------
Integrantes: Gabriel Di Buongrazio, Andrés Moncada

Computación I

Entrega Final

Universidad Central de Venezuela

Tema:   Análisis de la relación entre estadísticas de equipos de la NBA con más y menos victorias durante                    períodos de nueve años comprendido entre 1996 y 2023.

 
### Gráfico de dispersión 
```{r, echo=FALSE}
GráficoDF <- plot_ly(team_by_period_w_prom, x=~TEAM, y=~w_prom, name = "Victorias desde 1994 hasta 2023",color =~season_by_period, marker = list(size =10), type = "scatter", mode= "markers") 
GráficoDF
```




Primer Período
============================================================================
Column {data-width=500}
-----------------------------------------------------------------------

### Primer Período (Gráfico de barras)

```{r,echo=FALSE}
#Gráfico de barras de promedio de victorias de los equipos
GRAB1<- plot_ly(data=w_period_1,x=~TEAM, y=~w_prom, name = "Primer Período", marker = list(color = "red", size= 10)) %>% layout(title = "Media de victorias", xaxis = list(title="Equipos"), yaxis = list(title = "Victorias")) 
GRAB1
```

Column {data-width=500}
-----------------------------------------------------------------------

### Primer Período (Gráfico de caja y bigotes)

```{r,echo=FALSE}
GRAC10 <- ggplot(df_period1,aes(x=TEAM, y=W, color=TEAM)) + geom_boxplot(size=3.0) + theme_classic() 
ggplotly(GRAC10 = ggplot2::last_plot(), tooltip = "all", layerData = 1, OriginalData= TRUE, heigth=NULL, width = NULL)

```

Segundo Período
============================================================================
Column {data-width=500} 
-----------------------------------------------------------------------

### Segundo Período (Gráfico de barras)

```{r,echo=FALSE}
#Gráfico de barras de promedio de victorias de los equipos
GRAB2<- plot_ly(data=w_period_2,x=~TEAM, y=~w_prom, name = "Segundo Período", marker = list(color = "green", size= 10)) %>% layout(title = "Media de victorias", xaxis = list(title="Equipos"), yaxis = list(title = "Victorias"))
GRAB2
```
 marker = list(color = "red", size= 10))

Column {data-width=500}}
-----------------------------------------------------------------------

### Segundo Período (Gráfico de caja y bigotes)

```{r,echo=FALSE}
#Gráfico de caja y bigotes de equipos con mas y menos victorias en promedio
GRAC20 <- ggplot(df_period2,aes(x=TEAM, y=W, color=TEAM)) + geom_boxplot(size=3.0) + theme_classic() 
ggplotly(GRAC20 = ggplot2::last_plot(), tooltip = "all", layerData = 1, OriginalData= TRUE, heigth=NULL, width = NULL)
```

Tercer Período
============================================================================
Column {data-width=500}
-----------------------------------------------------------------------

### Tercer Período (Gráfico de barras)

```{r,echo=FALSE}
#Gráfico de barras de promedio de victorias de los equipos
GRAB3<- plot_ly(data=w_period_3_,x=~TEAM, y=~w_prom, name = "Tercer Período", marker = list(color = "black", size= 10)) %>% layout(title = "Media de victorias", xaxis = list(title="Equipos "), yaxis = list(title = "Victorias"))
GRAB3
```

Column {data-width=500}
-----------------------------------------------------------------------

### Tercer Período (Gráfico de caja y bigotes)

```{r,echo=FALSE}
#Gráfico de caja y bigotes de equipos con mas y menos victorias en promedio
GRAC30 <- ggplot(df_period3,aes(x=TEAM, y=W, color=TEAM)) + geom_boxplot(size=3.0) + theme_classic() 
ggplotly(GRAC30 = ggplot2::last_plot(), tooltip = "all", layerData = 1, OriginalData= TRUE, heigth=NULL, width = NULL)
```
